name: pocket_chess
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  chess: ^0.8.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.0
  chessground: ^9.0.0
  dartchess: ^0.12.3
  fast_immutable_collections: ^11.2.0
  flutter_svg: ^2.2.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  stockfish: ^1.8.1
  uuid: ^4.5.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pieces/alfonso/
    - assets/pieces/alila/
    - assets/pieces/alpha/
    - assets/pieces/atopdown/
    - assets/pieces/california/
    - assets/pieces/cardinal/
    - assets/pieces/cburnett/
    - assets/pieces/celtic/
    - assets/pieces/chess7/
    - assets/pieces/chessicons/
    - assets/pieces/chessmonk/
    - assets/pieces/chessnut/
    - assets/pieces/companion/
    - assets/pieces/dubrovny/
    - assets/pieces/eyes/
    - assets/pieces/fantasy/
    - assets/pieces/fantasy_alt/
    - assets/pieces/freak/
    - assets/pieces/freestaunton/
    - assets/pieces/fresca/
    - assets/pieces/gioco/
    - assets/pieces/governor/
    - assets/pieces/horsey/
    - assets/pieces/icpieces/
    - assets/pieces/kilfiger/
    - assets/pieces/kosal/
    - assets/pieces/leipzig/
    - assets/pieces/letter/
    - assets/pieces/libra/
    - assets/pieces/maestro/
    - assets/pieces/magnetic/
    - assets/pieces/makruk/
    - assets/pieces/maya/
    - assets/pieces/merida/
    - assets/pieces/merida_new/
    - assets/pieces/metaltops/
    - assets/pieces/pirat/
    - assets/pieces/pirouetti/
    - assets/pieces/pixel/
    - assets/pieces/prmi/
    - assets/pieces/regular/
    - assets/pieces/reillycraig/
    - assets/pieces/riohacha/
    - assets/pieces/shapes/
    - assets/pieces/sittuyin/
    - assets/pieces/skulls/
    - assets/pieces/spatial/
    - assets/pieces/staunty/
    - assets/pieces/tatiana/
